from datetime import datetime, timedelta

# fmt: off

ELECTION_KEYWORDS = [
    "election",
    "vote",
    "voting",
    "ballot",
    "campaign",
    "candidate",
    "poll",
    "parliament",
    "mayor",
    "ward",
    "constituency",
    "nepali congress",
    "congress",
    "nc",
    "nepali congress party",
    "cpn uml",
    "uml",
    "cpn-uml",
    "communist party of nepal uml",
    "unified marxist leninist",
    "cpn (uml)",
    "maoist centre",
    "cpn maoist centre",
    "maoist",
    "nepal communist party",
    "ncp",
    "prachanda party",
    "rashtriya swatantra party",
    "rstriya swatantra party",
    "rsp",
    "rastriya swatantra party",
    "national independent party",
    "rpp",
    "rashtriya prajatantra party",
    "rastriya prajatantra party",
    "kp sharma oli",
    "kp oli",
    "k p sharma oli",
    "khadga prasad oli",
    "oli",
    "gagan thapa",
    "gagan kumar thapa",
    "thapa",
    "gagan",
    "balendra shah",
    "balen shah",
    "balen",
    "balendra",
    "pushpa kamal dahal",
    "prachanda",
    "dahal",
    "rabi lamichhane",
    "rabi",
    "lamichhane",
    "sher bahadur deuba",
    "deuba",
    "rajendra lingden",
    "lingden",
    "upendra yadav",
    "swarnim wagle",
    "ck raut",
    "former prime minister",
    "ex prime minister",
    "pm candidate",
    "prime ministerial candidate",
    "old guard",
    "veteran leader",
    "aging elite",
    "revolving leaders",
    "youth leader",
    "younger candidate",
    "new faces",
    "gen z favorite",
    "rapper turned politician",
    "former mayor",
    "kathmandu mayor",
    "communist leader",
    "maoist leader",
    "centrist",
    "liberal democratic",
    "party president",
    "party chairperson",
    "party leader",
    "jhapa 5",
    "jhapa-5",
    "chitwan 2",
    "chitwan-2",
]

# fmt:on


def is_recent(date_obj):
    two_months_ago = datetime.now() - timedelta(days=60)
    return date_obj >= two_months_ago

def contains_election_keywords(text):
    text = text.lower()
    return any(keyword in text for keyword in ELECTION_KEYWORDS)
